version: "3.3"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"
  db:
    image: mysql
    restart: always
    ports: 
      - 3308:3306 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
  phpmyadmin:
    image: phpmyadmin
    links:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1