export const TokensData = 
[
    {
        hasSomething:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'instituicao',
        cutSequence:'\nMEMORANDO no.',
    },
    {
        hasSomething:false,
        typeofdata:'number',
        maxamountcharacters:0,
        TokenName: 'numero',
        cutSequence:'\n',
    },
    {
        hasSomething:false,
        typeofdata:'string',
        maxamountcharacters:0,
        TokenName: 'local',
        cutSequence:', ',
    },
    {
        hasSomething:false,
        typeofdata:'number',
        maxamountcharacters:2,
        TokenName: 'dia',
        cutSequence:' de ',
    },
    {
        hasSomething:false,
        typeofdata:'string',
        maxamountcharacters:0,
        TokenName: 'mes',
        cutSequence:' de ',
    }, 
    {
        hasSomething:false,
        typeofdata:'number',
        maxamountcharacters:4,
        TokenName: 'ano',
        cutSequence:'.\n\nDe: Departamento',
    },
    {
        hasSomething:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName:'depto_proponente',
        cutSequence:'\nPara: Departamento',
    },

    {
        hasSomething:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'depto_dest',
        cutSequence:' /',
    },
    {
        hasSomething:false,
        typeofdata:'string',
        maxamountcharacters:0,
        TokenName: 'pronome_tratamento',
        cutSequence:'. ',
    },
    {
        hasSomething:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'cargo_dest',
        cutSequence:' ',
    },
    {
        hasSomething:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'nome_dest',
        cutSequence:'\nAssunto:',
    },
    {
        hasSomething:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'assunto',
        cutSequence:'\n\n',
    },
    {
        hasSomething:false,
        typeofdata:'string',
        maxamountcharacters:0,
        TokenName: 'pronome_tratamento',
        cutSequence:'.',
    },
   
    {
        hasSomething:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'cargo_dest',
        cutSequence:'\n',
    },
    {
        hasSomething:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'descricao',
        cutSequence:'\n\nAtenciosamente,\n\n',
    },
    {
        hasSomething:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'nome_proponente',
        cutSequence:'\n',
    },
    {
        hasSomething:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'cargo_proponente',
        cutSequence:' do Departamento',
    },
    {
        hasSomething:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'depto_proponente',
        cutSequence:'\n',
    },
]