export const TokensData = 
[
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'instituicao',
        TokenValue:'',
        cutSequence:'\nMEMORANDO no. ',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'number',
        maxamountcharacters:0,
        TokenName: 'numero',
        TokenValue:'',
        cutSequence:'\n',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string',
        maxamountcharacters:0,
        TokenName: 'local',
        TokenValue:'',
        cutSequence:', ',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'number',
        maxamountcharacters:2,
        TokenName: 'dia',
        TokenValue:'',
        cutSequence:' de ',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'month',
        maxamountcharacters:0,
        TokenName: 'mes',
        TokenValue:'',
        cutSequence:' de ',
    }, 
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'number',
        maxamountcharacters:4,
        TokenName: 'ano',
        TokenValue:'',
        cutSequence:'.\n\nDe: Departamento ',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName:'depto_proponente',
        TokenValue:'',
        cutSequence:'\nPara: Departamento ',
    },

    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'depto_dest',
        TokenValue:'',
        cutSequence:' / ',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string',
        maxamountcharacters:0,
        TokenName: 'pronome_tratamento',
        TokenValue:'',
        cutSequence:'. ',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'cargo_dest',
        TokenValue:'',
        cutSequence:' ',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'nome_dest',
        TokenValue:'',
        cutSequence:'\nAssunto: ',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'assunto',
        TokenValue:'',
        cutSequence:'\n\n',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string',
        maxamountcharacters:0,
        TokenName: 'pronome_tratamento',
        TokenValue:'',
        cutSequence:'. ',
    },
   
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'cargo_dest',
        TokenValue:'',
        cutSequence:'\n',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'descricao',
        TokenValue:'',
        cutSequence:'\n\nAtenciosamente,\n\n',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'nome_proponente',
        TokenValue:'',
        cutSequence:'\n',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'cargo_proponente',
        TokenValue:'',
        cutSequence:' do Departamento ',
    },
    {
        hasSomething:false,
        isDefined:false,
        typeofdata:'string&number',
        maxamountcharacters:0,
        TokenName: 'depto_proponente',
        TokenValue:'',
        cutSequence:'.',
    },
]

export const months = [
    'jan',
    'fev',
    'mar',
    'abr',
    'mai',
    'jun',
    'jul',
    'ago',
    'set',
    'out',
    'nov',
    'dez',
]